### ISSUE TITLE
GitHubで貼り付けた時に、パースがうまくできないことがある

### ISSUE THREAD

**Issue by yinm** [hypermkt/CopyAsMarkdownForSequelProBundle#8]
いつも使わせてもらってます！ありがとうございます！

ちゃんとは確認はできてないですが、以下の場合にパースがうまくいかないっぽいです。

`URLなど|数字` -> 1つのカラムに入ってしまうため、以降のカラムがずれる
`||`(項目がNULLの場合) -> 以降のカラムがパースされない 

解決方法としては、`| `の後にスペースを入れれば良さそうかなと思ってます。
時間見つけてPR作ってみますね。

**Comment by hypermkt** [comment]
Issueありがとうございます！再現するか自分も確認してみます。

**Comment by yinm** [comment]
再現確認してみました。
どうやら、GitHubだと問題ないのですが、GH:Eだと起きるみたいです・・・と思って、コードも直したのですが、今日試すと直ってそうでした・・・！
なので、このissueはクローズしますね。

---

せっかくなので、現象のパターンだけ書いておきます。

### データがブランクのカラム以降は、データが表示されない
e.g. 3以降のデータが表示されなくなる

|1|2|3|4
|---|---|---|---|
|a|b||d

### URL + 数字だと、データが1つになる
3と4のカラムが1つのカラムになる (4以降が前のカラムにずれてしまう)

|1|2|3|4|5
|---|---|---|---|---
|a|b|http://test.com|1|e

**Comment by hypermkt** [comment]
あら、直っていたとのことで了解です！

確かにGitHub/GHE共に、再現コードを試しても正常に表示されますねぇ。ご確認ありがとうございました！
